# Generated by Django 5.1.7 on 2025-09-16 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_movimiento_fecha_alter_movimiento_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ['fecha', 'id']},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_registro',
        ),
        migrations.AddField(
            model_name='movimiento',
            name='saldo',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.categoria'),
        ),
    ]
