# Generated by Django 5.1.7 on 2025-10-11 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_alter_movimiento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Reportes',
                'verbose_name_plural': 'Reportes',
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('productos.producto',),
        ),
        migrations.AlterModelOptions(
            name='movimiento',
            options={'ordering': ['fecha', 'id'], 'permissions': [('ver_reportes', 'Puede ver el módulo de reportes')]},
        ),
    ]
